export default {
  dcApi: {
    input: './openapi.json',
    output: {
      target: './src/api/generated/index.ts',
      client: 'fetch',
      clean: true,
      prettier: true,
      override: {
        header: () => [
          'Generated by orval - DO NOT EDIT',
          'import { requestWrapper } from \'../generatedWrapper\'',
        ],
      },
    },
  },
};
